site_name: benchmark-tool
site_url: https://potassco.org/systems/benchmark-tool
site_description:
repo_name: potassco/benchmark-tool
repo_url: https://github.com/potassco/benchmark-tool
copyright: Copyright &copy; 2025 Potassco

extra_css:
  - _custom/css/extra.css
  - _custom/css/mkdocstrings.css
  - _custom/css/mkdoclingo.css

extra_javascript:
  - _custom/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  logo: assets/images/potassco-logo.svg
  custom_dir: docs/_custom/overrides
  favicon: assets/images/potassco-logo-dark.svg
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    - navigation.indexes
    - content.code.annotate
    # - toc.integrate
    - toc.follow
    - navigation.path
    # - navigation.top
    - navigation.tabs
    - content.code.copy
    - content.tooltips
    # - navigation.instant.preview
    # - navigation.expand
  icon:
    repo: fontawesome/brands/github
    admonition:
      quote: material/file-code-outline
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: indigo # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: indigo # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/potassco/benchmark-tool
    - icon: potassco-logo
      link: https://potassco.org
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - _custom/overrides/.icons
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - footnotes

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            # show_root_toc_entry: false
            # show_inherited_summary: true
            show_inherited_detail: true
            show_inherited_detail_toc: true
            show_inherited_detail_tree: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_source: false

nav:
  - Home: index.md
  - Getting Started: 
     - getting_started/index.md
     - bgen:
       - getting_started/bgen/index.md
       - Runscript: getting_started/bgen/runscript.md
       - Templates: getting_started/bgen/templates.md
     - beval:
       - getting_started/beval/index.md
     - bconv:
       - getting_started/bconv/index.md
  - Examples: examples/index.md
  - Reference:
    - reference/index.md
    - Encoding Support: reference/encoding_support.md
    - Modifying the Resultparser: reference/resultparser.md
    - API: 
      - reference/api/index.md
      - Runscript Components:
        - reference/api/runscript/index.md
        - Classes: reference/api/runscript/runscript.md
        - Parser: reference/api/runscript/parser.md
      - Resultparser Modules: reference/api/resultparser.md
      - Result Components:
        - reference/api/result/index.md
        - Classes: reference/api/result/result.md
        - Parser: reference/api/result/parser.md
        - ODS Gen: reference/api/result/ods_gen.md
      - Tools: reference/api/tools.md
      - Entry Points: reference/api/entry_points.md
  - Community:
    - community/index.md
    - Help: community/help.md
    - Contributing: community/CONTRIBUTING.md